# Generated by Django 4.2.7 on 2023-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
