# Generated by Django 4.2.5 on 2023-12-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
