# Generated by Django 4.2.7 on 2023-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0019_modelimage_modelprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
