# Generated by Django 4.2.7 on 2023-12-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0020_modelprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
