# Generated by Django 4.2.7 on 2023-12-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0021_modelprofile_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherDatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='model_display_images/')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
