# Generated by Django 4.2.7 on 2023-12-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0022_anotherdatabasemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotherdatabasemodel',
            name='image',
        ),
    ]
