# Generated by Django 4.2.7 on 2023-12-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0023_remove_anotherdatabasemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='image_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
