# Generated by Django 4.2.7 on 2023-12-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0024_anotherdatabasemodel_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotherdatabasemodel',
            name='image_id',
        ),
    ]
