# Generated by Django 4.2.7 on 2023-12-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0025_remove_anotherdatabasemodel_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoapp.modelimage'),
        ),
    ]
