# Generated by Django 4.2.7 on 2023-12-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0026_anotherdatabasemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='model_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoapp.modelprofile'),
        ),
    ]
