# Generated by Django 4.2.7 on 2023-12-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0027_anotherdatabasemodel_model_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
