# Generated by Django 4.2.7 on 2024-01-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0029_anotherdatabasemodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='height',
            field=models.FloatField(default=0.0),
        ),
    ]
