# Generated by Django 4.2.7 on 2024-01-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0030_anotherdatabasemodel_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
