# Generated by Django 4.2.7 on 2024-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0031_modelprofile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='Chest0round',
            field=models.FloatField(default=0.0),
        ),
    ]
