# Generated by Django 4.2.7 on 2024-01-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0032_modelprofile_chest0round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprofile',
            name='Chest0round',
        ),
    ]
