# Generated by Django 4.2.7 on 2024-01-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0033_remove_modelprofile_chest0round'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='Chestround',
            field=models.FloatField(default=0.0),
        ),
    ]
