# Generated by Django 4.2.7 on 2024-01-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0034_modelprofile_chestround'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='Shouldertoshoulder',
            field=models.FloatField(default=0.0),
        ),
    ]
