# Generated by Django 4.2.7 on 2024-01-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0035_modelprofile_shouldertoshoulder'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='Hipround',
            field=models.FloatField(default=0.0),
        ),
    ]
