# Generated by Django 4.2.7 on 2024-01-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0036_modelprofile_hipround'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='Armhole',
            field=models.FloatField(default=0.0),
        ),
    ]
