# Generated by Django 4.2.7 on 2024-01-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0037_modelprofile_armhole'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='Waistround',
            field=models.FloatField(default=0.0),
        ),
    ]
