# Generated by Django 4.2.7 on 2024-01-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0039_modelprofile_female_measurements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='Armhole',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='Chestround',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='Hipround',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='Shouldertoshoulder',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='Waistround',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anotherdatabasemodel',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
