# Generated by Django 4.2.7 on 2024-01-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0047_order_section_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_section',
        ),
    ]
