# Generated by Django 4.2.7 on 2024-01-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0049_order_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_section',
        ),
    ]
