# Generated by Django 4.2.7 on 2024-01-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0051_order_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_sections',
            name='user',
        ),
    ]
