# Generated by Django 4.2.7 on 2024-01-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0056_order_sections_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
                ('image', models.ImageField(upload_to='swiper_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='swiper_videos/')),
            ],
        ),
    ]
