# Generated by Django 4.2.7 on 2024-01-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0057_swipercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
                ('image', models.ImageField(upload_to='fashion_section/')),
            ],
        ),
        migrations.CreateModel(
            name='FashionSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
                ('image', models.ImageField(upload_to='fashion_section2/')),
            ],
        ),
    ]
