# Generated by Django 4.2.7 on 2024-01-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0058_fashionsection_fashionsection2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fashion_images/')),
                ('heading', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
