# Generated by Django 4.2.7 on 2024-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoapp', '0059_fashioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashioncontent',
            name='background_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
